services:
  - type: web
    name: edutech-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://username:password@cluster.mongodb.net/edutech?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: your_jwt_secret_key_here
      - key: PORT
        value: 4000
